# pyproject.toml
[tool.black]
line-length = 192
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.poe.tasks]

format = { shell = "black . && isort . && flake8 ." }

run = { shell = "python manage.py runserver" }

makemigrations = { shell = "python manage.py makemigrations" }
migrate = { shell = "python manage.py migrate" }