# Generated by Django 5.2.4 on 2025-07-26 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="file",
            name="sensitivity",
            field=models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="low", max_length=20),
        ),
        migrations.CreateModel(
            name="AnomalyLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anomaly_type", models.CharField(max_length=100)),
                ("detail", models.TextField()),
                ("severity", models.IntegerField(default=1)),
                ("access_log", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="monitor.accesslog")),
            ],
        ),
    ]
