# Generated by Django 5.2.4 on 2025-07-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
