# Generated by Django 5.2.4 on 2025-07-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_rename_name_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="risk_score",
            field=models.IntegerField(default=0),
        ),
    ]
