# Generated by Django 5.2.4 on 2025-07-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0006_user_risk_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="file_access_history",
            field=models.ManyToManyField(related_name="user_history", through="monitor.AccessLog", to="monitor.file"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="flagged_for_ip_mismatch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="trust_level",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="file",
            name="sensitivity",
            field=models.CharField(choices=[("public", "Public"), ("internal ", "Internal"), ("confidential", "Confidential"), ("classified", "Classified")], default="public", max_length=20),
        ),
    ]
