# Generated by Django 5.2.4 on 2025-07-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0007_user_file_access_history_user_first_ip_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="first_ip",
            new_name="home_ip",
        ),
    ]
