# Generated by Django 5.2.4 on 2025-07-29 12:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0008_rename_first_ip_user_home_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="trusted_ips",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, default=list, size=None),
        ),
    ]
